services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meet-up-web
    ports:
      - '3000:3000'
    # env_file:
    #   - .env
    environment:
      - NODE_ENV=production
